### ISSUE TITLE
一个改进建议

### ISSUE THREAD

**Issue by topinking2** [hongliuliao/thrift-generator#2]
生成service方法的时候，没有保留参数名称

我javaservice里面的方法签名是
public GroupMemberListResult getAllGroupMembers(String userId, String groupId);

service里面就变成了
GroupMemberListResult getAllGroupMembers(1:string arg0,2:string arg1)

能否借用javassist这类工具通过反射把参数名获取过来?
不然，生成的thrift文件还要修改下参数名才方便使用

感谢

**Comment by hongliuliao** [comment]
昨天已经把功能加上了, 参考命令
```
mvn test -Dtest=com.sohu.thrift.generator.builder.ThriftStructBuilderTest
```
