### ISSUE TITLE
如果接口参数涉及到继承问题public class AccDo extends User

### ISSUE THREAD

**Issue by wad12302** [hongliuliao/thrift-generator#3]
`public class AccDo extends User {

	private String testExtends;

	public String getTestExtends() {

		return testExtends;
	}

	public void setTestExtends(String testExtends) {
		this.testExtends = testExtends;
	}

}
`
无法构造：
	public User loginDo(AccDo ddvo);

AccDo 实体

**Comment by hongliuliao** [comment]
谢谢反馈, 已修复
