### ISSUE TITLE
对java自定义的泛型对象编译失败

### ISSUE THREAD

**Issue by chLei** [hongliuliao/thrift-generator#4]
如果我的在接口定义的一个方法里面，返回一个自定义的带泛型的对象，类似ReturnResult<User>
public class ReturnResult<T> implements Serializable {
	private String desc = null;
	private int code = 0;
	private T returnContent;
}
程序处理失败

**Comment by chLei** [comment]
尖括号都给过滤掉了。。。ReturnResult《User》

**Comment by chLei** [comment]
尖括号都给过滤掉了。。。public class ReturnResult《T》   返回ReturnResult《User》

**Comment by hongliuliao** [comment]
这个是因为thrift不支持自定义对象的泛型, 具体可参考此文档 : http://thrift.apache.org/docs/idl

**Comment by hongliuliao** [comment]
已增加对这种情况下的错误提示信息
