### ISSUE TITLE
list<enum> bug

### ISSUE THREAD

**Issue by imxuelei** [hongliuliao/thrift-generator#6]
List<`TestEnum`> testEnum  => list<`enum`>testEnum

**Comment by hongliuliao** [comment]
感谢反馈, 相关修改及测试用例: https://github.com/hongliuliao/thrift-generator/commit/a5409a3ad777e36a194593115d8d4b4c4eef27d1
运行测试命令: mvn test -Dtest=issue6.*

**Comment by imxuelei** [comment]
9月份我自己修复了，突然今天又用到工具，想起来给你说一声。
使用过后，提一些建议：
1.前后端分离，所以这个Thrift文件可以当做接口文档使用，我加了自定义注解，每个字段、方法、类都可以有注释，idl文件里有注释前端不需要其他文档。
2.Thrift service throw TException 这种情况没有处理。（正在考虑优化一下）
3.Double没有支持，Thrift是有double的。
4.由于getDeclaredMethods（）得到的无序数组，导致每次生成idl顺序可能不一致，diff有点多。建议Method排序。
![image](https://user-images.githubusercontent.com/23044113/33591813-a77a33fc-d9c2-11e7-8857-a03efbdbcb6e.png)
![image](https://user-images.githubusercontent.com/23044113/33591913-45f4ca2e-d9c3-11e7-9829-a4856adeadc3.png)

最后感谢开源！

**Comment by hongliuliao** [comment]
嗯, 你的建议很好, 也欢迎提交PR

**Comment by hongliuliao** [comment]
你说的几个问题, 都已经解决, 我单独创建了一个issue, 可以查看详情: https://github.com/hongliuliao/thrift-generator/issues/7
